///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace JpetStore
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the JpetStoreRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("dcc4c6ab-b0c4-48a8-9173-1d14873eeefd")]
    public partial class JpetStoreRepository : RepoGenBaseFolder
    {
        static JpetStoreRepository instance = new JpetStoreRepository();
        JpetStoreRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        JpetStoreRepositoryFolders.JPetStoreDemoMozillaFirefoxAppFolder _jpetstoredemomozillafirefox;
        JpetStoreRepositoryFolders.ParametresAppFolder _parametres;
        JpetStoreRepositoryFolders.ExplorerAppFolder _explorer;

        /// <summary>
        /// Gets the singleton class instance representing the JpetStoreRepository element repository.
        /// </summary>
        [RepositoryFolder("dcc4c6ab-b0c4-48a8-9173-1d14873eeefd")]
        public static JpetStoreRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public JpetStoreRepository() 
            : base("JpetStoreRepository", "/", null, 0, false, "dcc4c6ab-b0c4-48a8-9173-1d14873eeefd", ".\\RepositoryImages\\JpetStoreRepositorydcc4c6ab.rximgres")
        {
            _applicationundertest = new JpetStoreRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _jpetstoredemomozillafirefox = new JpetStoreRepositoryFolders.JPetStoreDemoMozillaFirefoxAppFolder(this);
            _parametres = new JpetStoreRepositoryFolders.ParametresAppFolder(this);
            _explorer = new JpetStoreRepositoryFolders.ExplorerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("dcc4c6ab-b0c4-48a8-9173-1d14873eeefd")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("684d1fde-bf8d-4987-bb98-878394c8049f")]
        public virtual JpetStoreRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The JPetStoreDemoMozillaFirefox folder.
        /// </summary>
        [RepositoryFolder("cfa74eaf-4509-4772-a776-ca0d809a08f3")]
        public virtual JpetStoreRepositoryFolders.JPetStoreDemoMozillaFirefoxAppFolder JPetStoreDemoMozillaFirefox
        {
            get { return _jpetstoredemomozillafirefox; }
        }

        /// <summary>
        /// The Parametres folder.
        /// </summary>
        [RepositoryFolder("8f72400e-965a-476b-86e0-8469284f7296")]
        public virtual JpetStoreRepositoryFolders.ParametresAppFolder Parametres
        {
            get { return _parametres; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("f5fbcfb0-a628-41a2-9d9d-7bf2d8ff2e65")]
        public virtual JpetStoreRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class JpetStoreRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("684d1fde-bf8d-4987-bb98-878394c8049f")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "684d1fde-bf8d-4987-bb98-878394c8049f", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("684d1fde-bf8d-4987-bb98-878394c8049f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("684d1fde-bf8d-4987-bb98-878394c8049f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The JPetStoreDemoMozillaFirefoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("cfa74eaf-4509-4772-a776-ca0d809a08f3")]
        public partial class JPetStoreDemoMozillaFirefoxAppFolder : RepoGenBaseFolder
        {
            JpetStoreRepositoryFolders.RowRowFolder _rowrow;
            JpetStoreRepositoryFolders.JPetStoreDemoFolder _jpetstoredemo;

            /// <summary>
            /// Creates a new JPetStoreDemoMozillaFirefox  folder.
            /// </summary>
            public JPetStoreDemoMozillaFirefoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("JPetStoreDemoMozillaFirefox", "/form[@title>'JPetStore Demo - Mozilla']", parentFolder, 30000, null, true, "cfa74eaf-4509-4772-a776-ca0d809a08f3", "")
            {
                _rowrow = new JpetStoreRepositoryFolders.RowRowFolder(this);
                _jpetstoredemo = new JpetStoreRepositoryFolders.JPetStoreDemoFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cfa74eaf-4509-4772-a776-ca0d809a08f3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cfa74eaf-4509-4772-a776-ca0d809a08f3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RowRow folder.
            /// </summary>
            [RepositoryFolder("17ded81d-0942-426a-b501-8539e876100d")]
            public virtual JpetStoreRepositoryFolders.RowRowFolder RowRow
            {
                get { return _rowrow; }
            }

            /// <summary>
            /// The JPetStoreDemo folder.
            /// </summary>
            [RepositoryFolder("95f321ed-f4a7-4e72-94c4-354e3940b93d")]
            public virtual JpetStoreRepositoryFolders.JPetStoreDemoFolder JPetStoreDemo
            {
                get { return _jpetstoredemo; }
            }
        }

        /// <summary>
        /// The RowRowFolder folder.
        /// </summary>
        [RepositoryFolder("17ded81d-0942-426a-b501-8539e876100d")]
        public partial class RowRowFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fisw01Info;
            RepoItemInfo _cellInfo;
            RepoItemInfo _text2Info;

            /// <summary>
            /// Creates a new RowRow  folder.
            /// </summary>
            public RowRowFolder(RepoGenBaseFolder parentFolder) :
                    base("RowRow", "container[@accessiblerole='Grouping']//container[@accessiblename='JPetStore Demo']//table[@accessiblerole='Table']/row[2]", parentFolder, 30000, null, false, "17ded81d-0942-426a-b501-8539e876100d", "")
            {
                _fisw01Info = new RepoItemInfo(this, "FISW01", "?/?/link[@accessiblename='FI-SW-01']/text[@accessiblename='FI-SW-01']", "", 30000, null, "28fe4dcd-08d1-49d8-af5a-d01fd6e37c18");
                _cellInfo = new RepoItemInfo(this, "Cell", "cell[5]", "", 30000, null, "97568c5d-d414-493d-bf6b-011d4531b06c");
                _text2Info = new RepoItemInfo(this, "Text2", "cell[5]/text[@accessiblerole='Text']", "", 30000, null, "75f039db-4d35-45f9-959c-256043c5ff0b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("17ded81d-0942-426a-b501-8539e876100d")]
            public virtual Ranorex.Row Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Row>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("17ded81d-0942-426a-b501-8539e876100d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FISW01 item.
            /// </summary>
            [RepositoryItem("28fe4dcd-08d1-49d8-af5a-d01fd6e37c18")]
            public virtual Ranorex.Text FISW01
            {
                get
                {
                    return _fisw01Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FISW01 item info.
            /// </summary>
            [RepositoryItemInfo("28fe4dcd-08d1-49d8-af5a-d01fd6e37c18")]
            public virtual RepoItemInfo FISW01Info
            {
                get
                {
                    return _fisw01Info;
                }
            }

            /// <summary>
            /// The Cell item.
            /// </summary>
            [RepositoryItem("97568c5d-d414-493d-bf6b-011d4531b06c")]
            public virtual Ranorex.Cell Cell
            {
                get
                {
                    return _cellInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Cell item info.
            /// </summary>
            [RepositoryItemInfo("97568c5d-d414-493d-bf6b-011d4531b06c")]
            public virtual RepoItemInfo CellInfo
            {
                get
                {
                    return _cellInfo;
                }
            }

            /// <summary>
            /// The Text2 item.
            /// </summary>
            [RepositoryItem("75f039db-4d35-45f9-959c-256043c5ff0b")]
            public virtual Ranorex.Text Text2
            {
                get
                {
                    return _text2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text2 item info.
            /// </summary>
            [RepositoryItemInfo("75f039db-4d35-45f9-959c-256043c5ff0b")]
            public virtual RepoItemInfo Text2Info
            {
                get
                {
                    return _text2Info;
                }
            }
        }

        /// <summary>
        /// The JPetStoreDemoFolder folder.
        /// </summary>
        [RepositoryFolder("95f321ed-f4a7-4e72-94c4-354e3940b93d")]
        public partial class JPetStoreDemoFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loginInfo;
            RepoItemInfo _cell1Info;
            RepoItemInfo _graphicInfo;
            RepoItemInfo _noneInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _text1Info;
            RepoItemInfo _signoutInfo;

            /// <summary>
            /// Creates a new JPetStoreDemo  folder.
            /// </summary>
            public JPetStoreDemoFolder(RepoGenBaseFolder parentFolder) :
                    base("JPetStoreDemo", "container[@accessiblerole='Grouping']/container[@accessiblerole='PropertyPage']/?/?/container[@accessiblename='JPetStore Demo']", parentFolder, 30000, null, false, "95f321ed-f4a7-4e72-94c4-354e3940b93d", "")
            {
                _loginInfo = new RepoItemInfo(this, "Login", ".//button[@accessiblename='Login']", "", 30000, null, "8773ae63-9a64-4525-85f7-7177f69e8296");
                _cell1Info = new RepoItemInfo(this, "Cell1", ".//table[@accessiblerole='Table']/row[3]/cell[1]", "", 30000, null, "2711b2da-c0e1-4dda-b947-8ac8cf59af25");
                _graphicInfo = new RepoItemInfo(this, "Graphic", "element[2]/element[2]/element[1]/element[@accessiblerole='None']/link[1]/picture[@accessiblerole='Graphic']", "element[@accessiblerole='None']/link[1]/picture[@accessiblerole='Graphic']", 30000, null, "1f03787b-28d0-4010-aa62-3c907dac56eb");
                _noneInfo = new RepoItemInfo(this, "None", "element[2]/element[@accessiblerole='None']/element[@accessiblerole='None']", "", 30000, null, "a1d31bb2-26c2-400e-bc23-c9f25b7a33c2");
                _textInfo = new RepoItemInfo(this, "Text", "element[2]/element[@accessiblerole='None']/element[@accessiblerole='None']/element[2]/text[2]", "element[2]/text[2]", 30000, null, "15599b6b-9b51-4856-aa2f-cf56a8dfbb36");
                _text1Info = new RepoItemInfo(this, "Text1", "element[2]/element[@accessiblerole='None']/element[@accessiblerole='None']/element[2]/text[4]", "element[2]/text[4]", 30000, null, "acbd9395-ca26-41ca-b5c7-210f23cc3f41");
                _signoutInfo = new RepoItemInfo(this, "SignOut", ".//link[@accessiblename='Sign Out']/text[@accessiblename='Sign Out']", "", 30000, null, "b1c2f1df-6eb8-4601-a034-1b2ed1e2bb5c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("95f321ed-f4a7-4e72-94c4-354e3940b93d")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("95f321ed-f4a7-4e72-94c4-354e3940b93d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("8773ae63-9a64-4525-85f7-7177f69e8296")]
            public virtual Ranorex.Button Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("8773ae63-9a64-4525-85f7-7177f69e8296")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The Cell1 item.
            /// </summary>
            [RepositoryItem("2711b2da-c0e1-4dda-b947-8ac8cf59af25")]
            public virtual Ranorex.Cell Cell1
            {
                get
                {
                    return _cell1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Cell1 item info.
            /// </summary>
            [RepositoryItemInfo("2711b2da-c0e1-4dda-b947-8ac8cf59af25")]
            public virtual RepoItemInfo Cell1Info
            {
                get
                {
                    return _cell1Info;
                }
            }

            /// <summary>
            /// The Graphic item.
            /// </summary>
            [RepositoryItem("1f03787b-28d0-4010-aa62-3c907dac56eb")]
            public virtual Ranorex.Picture Graphic
            {
                get
                {
                    return _graphicInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The Graphic item info.
            /// </summary>
            [RepositoryItemInfo("1f03787b-28d0-4010-aa62-3c907dac56eb")]
            public virtual RepoItemInfo GraphicInfo
            {
                get
                {
                    return _graphicInfo;
                }
            }

            /// <summary>
            /// The None item.
            /// </summary>
            [RepositoryItem("a1d31bb2-26c2-400e-bc23-c9f25b7a33c2")]
            public virtual Ranorex.Unknown None
            {
                get
                {
                    return _noneInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None item info.
            /// </summary>
            [RepositoryItemInfo("a1d31bb2-26c2-400e-bc23-c9f25b7a33c2")]
            public virtual RepoItemInfo NoneInfo
            {
                get
                {
                    return _noneInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("15599b6b-9b51-4856-aa2f-cf56a8dfbb36")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("15599b6b-9b51-4856-aa2f-cf56a8dfbb36")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("acbd9395-ca26-41ca-b5c7-210f23cc3f41")]
            public virtual Ranorex.Text Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("acbd9395-ca26-41ca-b5c7-210f23cc3f41")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The SignOut item.
            /// </summary>
            [RepositoryItem("b1c2f1df-6eb8-4601-a034-1b2ed1e2bb5c")]
            public virtual Ranorex.Text SignOut
            {
                get
                {
                    return _signoutInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SignOut item info.
            /// </summary>
            [RepositoryItemInfo("b1c2f1df-6eb8-4601-a034-1b2ed1e2bb5c")]
            public virtual RepoItemInfo SignOutInfo
            {
                get
                {
                    return _signoutInfo;
                }
            }
        }

        /// <summary>
        /// The ParametresAppFolder folder.
        /// </summary>
        [RepositoryFolder("8f72400e-965a-476b-86e0-8469284f7296")]
        public partial class ParametresAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Parametres  folder.
            /// </summary>
            public ParametresAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Parametres", "/form[@name='Paramètres']", parentFolder, 30000, null, true, "8f72400e-965a-476b-86e0-8469284f7296", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8f72400e-965a-476b-86e0-8469284f7296")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8f72400e-965a-476b-86e0-8469284f7296")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("f5fbcfb0-a628-41a2-9d9d-7bf2d8ff2e65")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _list1Info;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/desktop[@processname='explorer']", parentFolder, 30000, null, true, "f5fbcfb0-a628-41a2-9d9d-7bf2d8ff2e65", "")
            {
                _list1Info = new RepoItemInfo(this, "List1", "?/?/list[@automationid='1']", "?/?/list[@automationid='1']", 30000, null, "7a542399-de30-4df0-8055-fd7a95550c7d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f5fbcfb0-a628-41a2-9d9d-7bf2d8ff2e65")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f5fbcfb0-a628-41a2-9d9d-7bf2d8ff2e65")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The List1 item.
            /// </summary>
            [RepositoryItem("7a542399-de30-4df0-8055-fd7a95550c7d")]
            public virtual Ranorex.List List1
            {
                get
                {
                    return _list1Info.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The List1 item info.
            /// </summary>
            [RepositoryItemInfo("7a542399-de30-4df0-8055-fd7a95550c7d")]
            public virtual RepoItemInfo List1Info
            {
                get
                {
                    return _list1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
