///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace JpetStore
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("c9197e34-2576-4c38-b656-3f7320f99186", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the JpetStoreRepository repository.
        /// </summary>
        public static JpetStoreRepository repo = JpetStoreRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'j' with focus on 'JPetStoreDemoMozillaFirefox'.", repo.JPetStoreDemoMozillaFirefox.SelfInfo, new RecordItemIndex(0));
            repo.JPetStoreDemoMozillaFirefox.Self.EnsureVisible();
            Keyboard.Press("j");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad2}ee' with focus on 'JPetStoreDemoMozillaFirefox.JPetStoreDemo.Text'.", repo.JPetStoreDemoMozillaFirefox.JPetStoreDemo.TextInfo, new RecordItemIndex(1));
            repo.JPetStoreDemoMozillaFirefox.JPetStoreDemo.Text.PressKeys("{NumPad2}ee");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JPetStoreDemoMozillaFirefox.JPetStoreDemo.Login' at 20;12.", repo.JPetStoreDemoMozillaFirefox.JPetStoreDemo.LoginInfo, new RecordItemIndex(2));
            repo.JPetStoreDemoMozillaFirefox.JPetStoreDemo.Login.Click("20;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JPetStoreDemoMozillaFirefox.JPetStoreDemo.Graphic' at 36;11.", repo.JPetStoreDemoMozillaFirefox.JPetStoreDemo.GraphicInfo, new RecordItemIndex(3));
            repo.JPetStoreDemoMozillaFirefox.JPetStoreDemo.Graphic.Click("36;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JPetStoreDemoMozillaFirefox.RowRow.FISW01' at 46;11.", repo.JPetStoreDemoMozillaFirefox.RowRow.FISW01Info, new RecordItemIndex(4));
            repo.JPetStoreDemoMozillaFirefox.RowRow.FISW01.Click("46;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JPetStoreDemoMozillaFirefox.RowRow.Cell' at 34;12.", repo.JPetStoreDemoMozillaFirefox.RowRow.CellInfo, new RecordItemIndex(5));
            repo.JPetStoreDemoMozillaFirefox.RowRow.Cell.Click("34;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JPetStoreDemoMozillaFirefox.RowRow.Text2' at 30;11.", repo.JPetStoreDemoMozillaFirefox.RowRow.Text2Info, new RecordItemIndex(6));
            repo.JPetStoreDemoMozillaFirefox.RowRow.Text2.Click("30;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{NumPad2}' with focus on 'JPetStoreDemoMozillaFirefox.RowRow.Text2'.", repo.JPetStoreDemoMozillaFirefox.RowRow.Text2Info, new RecordItemIndex(7));
            repo.JPetStoreDemoMozillaFirefox.RowRow.Text2.PressKeys("{Back}{NumPad2}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JPetStoreDemoMozillaFirefox.JPetStoreDemo.Cell1' at 164;16.", repo.JPetStoreDemoMozillaFirefox.JPetStoreDemo.Cell1Info, new RecordItemIndex(8));
            repo.JPetStoreDemoMozillaFirefox.JPetStoreDemo.Cell1.Click("164;16");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
